"""empty message

Revision ID: 4a22532a7f16
Revises: 946f481a9241
Create Date: 2021-06-19 22:34:33.267235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a22532a7f16'
down_revision = '946f481a9241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move_record', sa.Column('in_out_date', sa.DATETIME(), nullable=True))
    op.drop_column('move_record', 'in_date')
    op.drop_column('move_record', 'out_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('move_record', sa.Column('out_date', mysql.DATETIME(), nullable=True))
    op.add_column('move_record', sa.Column('in_date', mysql.DATETIME(), nullable=True))
    op.drop_column('move_record', 'in_out_date')
    # ### end Alembic commands ###
