"""empty message

Revision ID: 87fb7a87d824
Revises: 04faaa76bba0
Create Date: 2021-06-15 15:32:43.171856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fb7a87d824'
down_revision = '04faaa76bba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('first_second_mapping', sa.Column('operate_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('first_second_mapping', 'operate_date')
    # ### end Alembic commands ###
