"""empty message

Revision ID: 8dce12dc298f
Revises: 
Create Date: 2021-06-14 22:12:56.305355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dce12dc298f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_second_mapping',
    sa.Column('second_trace_code', sa.String(length=30), nullable=False),
    sa.Column('first_trace_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['first_trace_code'], ['vaccine.id'], ),
    sa.PrimaryKeyConstraint('second_trace_code')
    )
    op.alter_column('vaccine', 'kind_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.drop_column('vaccine', 'kind_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccine', sa.Column('kind_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.alter_column('vaccine', 'kind_name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.drop_table('first_second_mapping')
    # ### end Alembic commands ###
